reviews:
  path_instructions:
    - path: "**/*.js"
      instructions: "あなたはベテランエンジニアです。jsファイルのルートタグに従って、以下の通りレビュー観点を追加してください。ファイル全体行数が多い (コメント行を含まずに 300 行を超える) 場合、分割可能かどうかの観点をレビューに含め、可能であれば、指摘してください.Google の JavaScript style guide に従ってレビューし、不具合あれば指摘してください."